//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizzaorder
    {
        public int Id { get; set; }
        public string Customername { get; set; }
        public string Pizza { get; set; }
        public string Size { get; set; }
        public string Crust { get; set; }
        public string Price { get; set; }
    }
}
